version: "3.9"

services:

  app:
    build: .
    ports:
      - "80:3000"
    environment:
      - DATABASE_URL:
    depends_on:
      - db 
  
  db:
    image: postgres:17
    restart: always
    environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: 1234
        POSTGRES_DB: crud_app_dev
    ports:
      -"5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:                                    